import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "Basir",
      email: "admin@example.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: true,
      isSeller: true,
      seller: {
        name: "Puma",
        logo: "/uploads/1655303176690.jpg",
        description: "best seller",
        rating: 4.5,
        numReviews: 120,
      },
    },
    {
      name: "John",
      email: "user@example.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Nike Slim Shirt",
      category: "Shirts",
      image: "/uploads/1655303176690.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Adidas Fit Shirt",
      category: "Shirts",
      image: "/uploads/1655303186463.jpg",
      price: 100,
      countInStock: 20,
      brand: "Adidas",
      rating: 4.0,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Lacoste Free Shirt",
      category: "Shirts",
      image: "/uploads/1655303197046.jpg",
      price: 220,
      countInStock: 0,
      brand: "Lacoste",
      rating: 4.8,
      numReviews: 17,
      description: "high quality product",
    },
    {
      name: "Nike Slim Pant",
      category: "Pants",
      image: "/uploads/1655303210965.jpg",
      price: 78,
      countInStock: 15,
      brand: "Nike",
      rating: 4.5,
      numReviews: 14,
      description: "high quality product",
    },
    {
      name: "Puma Slim Pant",
      category: "Pants",
      image: "/uploads/1655303219395.jpg",
      price: 65,
      countInStock: 5,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Adidas Fit Pant",
      category: "Pants",
      image: "/uploads/1655303228345.jpg",
      price: 139,
      countInStock: 12,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 15,
      description: "high quality product",
    },
    {
      name: "Blue Jeans",
      category: "Pants",
      image: "/uploads/1655381094221.jpg",
      price: 500,
      countInStock: 20,
      brand: "Levis",
      rating: 4.5,
      numReviews: 15,
      description: "Sky blue jeans pant",
    },
    {
      name: "Cotton pant",
      category: "Pants",
      image: "/uploads/1655380725469.jpg",
      price: 500,
      countInStock: 15,
      brand: "Gap",
      rating: 4.5,
      numReviews: 15,
      description: "high quality branded pant",
    },
    {
      name: "Black Leather Coat",
      category: "Coat",
      image: "/uploads/1655382578265.jpg",
      price: 2000,
      countInStock: 20,
      brand: "Unknown",
      rating: 3,
      numReviews: 11,
      description: "Pure leather coat",
    },
    {
      name: "Blact Belt",
      category: "Accessories",
      image: "/uploads/1655448301166.jpg",
      price: 200,
      countInStock: 30,
      brand: "Unknown",
      rating: 2.6,
      numReviews: 15,
      description: "Black leather belt",
    },
  ],
};
export default data;
